//Types for GET FAQS
export const GET_FAQS_REQUEST_REQUEST = 'GET_FAQS_REQUEST_REQUEST';
export const GET_FAQS_REQUEST_SUCCESS = 'GET_FAQS_REQUEST_SUCCESS';
export const GET_FAQS_REQUEST_FAILURE = 'GET_FAQS_REQUEST_FAILURE';
//Types for GET Video URL
export const GET_VIDEO_URL_REQUEST_REQUEST = 'GET_VIDEO_URL_REQUEST_REQUEST';
export const GET_VIDEO_URL_REQUEST_SUCCESS = 'GET_VIDEO_URL_REQUEST_SUCCESS';
export const GET_VIDEO_URL_REQUEST_FAILURE = 'GET_VIDEO_URL_REQUEST_FAILURE';

//Types for SAVE PROFILE INFO
export const SAVE_PROFILE_INFO_REQUEST_REQUEST = 'SAVE_PROFILE_INFO_REQUEST';
export const SAVE_PROFILE_INFO_SUCCESS = 'SAVE_PROFILE_INFO_SUCCESS';
export const SAVE_PROFILE_INFO_FAILURE = 'SAVE_PROFILE_INFO_FAILURE';


//Types for SAVE PROFILE INFO
export const GET_PROFILE_INFO_REQUEST_REQUEST = 'GET_PROFILE_INFO_REQUEST';
export const GET_PROFILE_INFO_SUCCESS = 'GET_PROFILE_INFO_SUCCESS';
export const GET_PROFILE_INFO_FAILURE = 'GET_PROFILE_INFO_FAILURE';


export const SET_PROFILE_LOADER = 'SET_PROFILE_LOADER';
